name: eon_asset_tracker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-399.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: 
    git:
      url: https://github.com/theyakka/qr.flutter.git

  cupertino_icons: ^1.0.2
  crypto: ^3.0.2
  sidebarx: ^0.15.0
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  table_sticky_headers: ^2.0.5
  flutter_easyloading: ^3.0.5
  nanoid: ^1.0.0
  fl_chart: ^0.62.0
  printing: ^5.10.3
  pdf: ^3.10.1
  mysql_client: ^0.0.27
  path_provider: ^2.0.15
  path: ^1.8.3
  hive: ^2.2.3
  cryptography_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_path_converter: ^1.0.0
  import_sorter: ^4.6.0

flutter:

  uses-material-design: true

  assets:
    - fonts/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf